site_name: docs
site_url: https://docs.sephley.com
repo_name: docs
repo_url: https://github.com/sephley/docs
theme:
  name: material
  features:
  - content.code.copy
  - navigation.indexes
  - navigation.top
  - navigation.footer
  - navigation.tabs
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

site_description: My personal documentation
site_author: Sephley
copyright: All rights reserved
plugins:
  - glightbox
  - drawio
  - search
  - mkdocs-video

markdown_extensions: #requires pymdown-extensions + markdown in ci job
    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true

nav: #utilizes section feature for index pages
  - Home: index.md
  - ZLI-M109: 
    - zli-m109.md
  - BBW-M141: 
    - bbw-m141.md
    - Security: pruefung-security.md
    - Zusatz-Security: zusatz-pruefung.md
  - BBW-M169: 
    - bbw-m169.md
  - BBW-M300: 
    - bbw-m300.md
    - DHCP-PXE: dhcp.md
    - Mitschnitt-DHCP-PXE-Debian: pxe-mitschnitt.md
    - DNS:
      - dns/index.md
      - Glossar: 
        - dns/glossar/index.md
        - Anfänge-des-Internets: dns/glossar/beginning.md
        - Primary-Secondary-Konzept: dns/glossar/primsec.md
        - DNS-unter-IPv6: dns/glossar/dnsipv6.md
        - DynDNS: dns/glossar/dyndns.md
        - Record-Typen: dns/glossar/rectypes.md
        - Zonendatei: dns/glossar/zonefile.md
      - Praktisch: 
        - dns/praktisch/index.md
        - Bind9: dns/praktisch/bind9.md
        - Secondary-DNS: dns/praktisch/secdns.md
        - Persönliche-Subdomain: dns/praktisch/pers_subdomain.md
        - DNS-übersteuern: dns/praktisch/uebersteuern.md
        - Wireshark: dns/praktisch/wireshark.md
        - DNS-in-AWS: dns/praktisch/dnsaws.md
    - TLS:
      - tls/index.md
      - Glossar:
        - tls/glossar/index.md
        - Architektur: tls/glossar/architektur.md
        - Anwendungsfälle: tls/glossar/use-cases.md
        - Angriff-Abwehrmechanismus: tls/glossar/angriff-abwehr.md
        - Verschlüsslungsverfahren: tls/glossar/verschluesslungsverfahren.md
        - SNI: tls/glossar/sni.md
        - Nachteile: tls/glossar/nachteile.md
        - Wikipedia-Artikel: tls/glossar/wikipedia.md
      - Aufgaben:
        - tls/aufgaben/index.md
        - Wireshark: tls/aufgaben/wireshark.md
        - Nginx: tls/aufgaben/nginx.md
        - Vergleich-nach-Sicherheitslevel: tls/aufgaben/vergleich.md
      - Homelab:
        - tls/homelab/index.md
        - Traefik: tls/homelab/traefik.md
    - ACME:
      - acme/index.md
      - Glossar:
        - acme/glossar/index.md
        - Was-ist-ACME: acme/glossar/acme.md
        - Let's-Encrypt-Zertifikate: acme/glossar/lets-encrypt.md
        - Wildcard-Zertifikate: acme/glossar/wildcard.md
      - Aufgaben:
        - acme/aufgaben/index.md
        - Certbot-Basic: acme/aufgaben/certbot-basic.md
        - Certbot-mit-Cloudflare: acme/aufgaben/certbot-cloudflare.md
        - Certbot-mit-Bind9: acme/aufgaben/certbot-bind.md
      - Homelab:
        - acme/homelab/index.md
        - ACME-in-Traefik: acme/homelab/traefik.md
  - Experts-Kurs: 
    - experts.md
