site_name: docs
site_url: https://docs.sephley.com
repo_name: docs
repo_url: https://github.com/sephley/docs
theme:
  name: material
  features:
  - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

site_description: My personal documentation
site_author: Sephley
copyright: All rights reserved
plugins:
  - glightbox
  - drawio
  - exporter
  - exporter-pdf:
      concurrency: 8
      covers:
        front: resources/templates/covers/front.html.j2
        back: resources/templates/covers/back.html.j2
      stylesheets:
        - resources/stylesheets/pdf.scss
  - exporter-extras:
      buttons:
        - title: Download as PDF
          enabled: !!python/name:mkdocs_exporter.plugins.pdf.button.enabled
          icon: !!python/name:mkdocs_exporter.plugins.pdf.button.icon
          attributes:
            href: !!python/name:mkdocs_exporter.plugins.pdf.button.href
            download: !!python/name:mkdocs_exporter.plugins.pdf.button.download

nav:
  - Home: index.md
  - ZLI-M109: zli-m109.md
  - BBW-M141: 
    - Home: bbw-m141.md
    - Security: pruefung-security.md
    - Zusatz-Security: zusatz-pruefung.md
  - BBW-M169: bbw-m169.md
  - BBW-M300:
    - DHCP-PXE: dhcp.md
    - Mitschnitt-DHCP-PXE-Debian: pxe-mitschnitt.md
  - Experts-Kurs:
    - GitLab-Setup: experts.md
