site_name: docs
site_url: https://docs.sephley.com
repo_name: docs
repo_url: https://github.com/sephley/docs
theme:
  name: material
  features:
  - content.code.copy
  - navigation.indexes
  - navigation.top
  - navigation.footer
  - navigation.tabs
  markdown_extensions: #requires pymdown-extensions in ci job
    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

site_description: My personal documentation
site_author: Sephley
copyright: All rights reserved
plugins:
  - glightbox
  - drawio
  - search
  - mkdocs-video

nav:
  - Home: index.md
  - ZLI-M109: zli-m109.md
  - BBW-M141: 
    - bbw-m141.md
    - Security: pruefung-security.md
    - Zusatz-Security: zusatz-pruefung.md
  - BBW-M169: bbw-m169.md
  - BBW-M300: #utilizes section feature for index pages
    - bbw-m300.md
    - DHCP-PXE: dhcp.md
    - Mitschnitt-DHCP-PXE-Debian: pxe-mitschnitt.md
    - DNS:
      - dns/index.md
      - Theorie: 
        - dns/theorie/index.md
        - Anfänge-des-Internets: dns/theorie/beginning.md
        - DNS-in-AWS: dns/theorie/dnsaws.md
        - DNS-unter-IPv6: dns/theorie/dnsipv6.md
        - DynDNS: dns/theorie/dyndns.md
        - Primary-Secondary-Konzept: dns/theorie/primsec.md
        - Record-Typen: dns/theorie/rectypes.md
        - Zonendatei: dns/theorie/zonefile.md
      - Praktisch: 
        - dns/praktisch/index.md
        - Bind9: dns/praktisch/bind9.md
        - Persöhnliche-Subdomain: dns/praktisch/pers_subdomain.md
        - Secondary-DNS: dns/praktisch/secdns.md
        - DNS-übersteuern: dns/praktisch/uebersteuern.md
        - Wireshark: dns/praktisch/wireshark.md
  - Experts-Kurs: experts.md
